require("dotenv").config();
const mongoose = require("mongoose");
const bcrypt = require("bcryptjs");
const userSchema = require("../models/registrationSchema/User.Schema.js");
const brokerSchema = require("../models/broker/brokerSchema.js");
const envConfig = require("../config/envConfig.js");

const seedUsers = async () => {
  try {
    console.log("📡 Connecting to Database...");
    await mongoose.connect("mongodb://localhost:27017/tms");

    console.log("🗑 Clearing existing users...");
    await userSchema.deleteMany(); // Clear existing data before seeding
    const users = [
      {
        clientType: "individual",
        status: "pending",
        email: "armitathapa2005@gmail.com",
        mobileNumber: "9868976541",
        panNumber: "PA0918",
        password: bcrypt.hashSync("test123", 10),
        loginFirstTime: true,
        addresses: [
          {
            countryOfResidence: "China",
            state: "State 2",
            district: "District 1",
            municipality: "Kohalpur",
            wardNum: "6",
            street: "AadarshNagar",
            addressType: "Corporate Office",
          },
        ],
        depositoryInfo: [
          {
            BOID: "test",
          },
        ],
        bankingInfo: [
          {
            bankName: "Global IME Bank",
            branch: "Kohalpur",
            accountType: "Saving",
            accountNumber: "624634065",
          },
        ],
        documents: [
          {
            fileName: "test",
            fileUrl: "test",
          },
        ],
        individualDetails: {
          firstName: "Privik",
          middleName: "Thapa",
          lastName: "Magar",
          gender: "Male",
          dateOfBirthAD: "2001-01-01",
          dateOfBirthBS: "2058-01-01",
          fatherName: "Bikram Thapa",
          motherName: "Preeti Raskoti",
          grandfatherName: "Hari Bahadur Thapa Magar",
          maritalStatus: "Single",
          nationality: "Nepali",
          financialDetails: "Upto 5,00,000",
          isNRN: false,
          isMinor: false,
          isInvolvedInInvestmentCompany: true,
          citizenshipNumber: "12344",
          citizenshipIssuedDistrict: "test",
          citizenshipIssuedDateAD: "2020-10-10",
          citizenshipIssuedDateBS: "2080-10-10",
        },
        moneyLaunder: {
          isHighRankingPolitician: false,
          isRelatedToHighRankingPolitician: false,
          haveBenefieciary: false,
          felonyRecord: false,
        },
      },
      {
        clientType: "corporate",
        email: "privik@gmail.com",
        mobileNumber: "356742842",
        panNumber: "PAN54321",
        status: "verified",
        password: bcrypt.hashSync("privik", 10),
        isFirstLogin: false,
        companyDetails: {
          companyName: "Petal",
          companyType: "Private",
          companyRegistrationNum: "24549",
          isSubsidiary: false,
          isListed: false,
          companyRegistrationAD: "2025-12-05",
          companyRegistrationBS: "2081-12-04",
          contactNumber: "98526463362",
          companyCEOName: "Privik",
          companySecretaryName: "Preeti",
          companyRegistrationOffice: "Kohalpur",
          countryOfRegistration: "Nepal",
          typeOfBusiness: "Service",
          dateOfIncorporationAD: "2025-03-05",
          dateOfIncorporationBS: "2081-12-12",
          firstContactPersonName: "Preeti",
          firstContactFatherName: "Devendra",
          firstContactGrandfatherName: "Gagan",
          firstContactDesignation: "Executive",
          secondContactPersonName: "Bikram",
          secondContactFatherName: "Hari",
          secondContactGrandfatherName: "Ganga",
          secondContactDesignation: "Director",
          fax: "326316",
          companyWebsite: "wertyuij",
        },
        ownershipDetails: {
          firstName: "Privik",
          middleName: "Thapa",
          lastName: "Magar",
          designation: "Director",
          fatherName: "Bikram",
          grandfatherName: "Hari",
          panNumber: "326565",
          email: "privik@gmail.com",
          address: "Kohalpur",
          country: "Nepal",
          province: "Province 5",
          district: "Bardiya",
          municipality: "Kohalpur",
          wardNumber: "6",
          tole: "ShivaNagar",
          postalCode: "22904",
          phoneNumber1: "95541524164851",
          phoneNumber2: "972120.13021",
          citizenshipNumber: "624635641-526545-25",
          citizenshipIssueDistrict: "Banke",
          citizenshipIssueAD: "2025-03-05",
          citizenshipIssueBS: "2081-12-05",
          professionalQualification: "jhgnkhm",
          professionalExperience: "2",
          educationalQualification: "Graduate",
        },
      },
      {
        clientType: "corporate",
        email: "shagun@gmail.com",
        status: "pending",
        mobileNumber: "9845622355",
        panNumber: "215245",
        password: bcrypt.hashSync("shagun", 10),
        isFirstLogin: true,
        companyDetails: {
          companyName: "Petal",
          companyType: "Public Ltd.",
          companyRegistrationNum: "24549",
          isSubsidiary: false,
          isListed: false,
          companyRegistrationAD: "2025-12-05",
          companyRegistrationBS: "2081-12-04",
          contactNumber: "98526463362",
          companyCEOName: "Privik",
          companySecretaryName: "Preeti",
          companyRegistrationOffice: "Kohalpur",
          countryOfRegistration: "Nepal",
          typeOfBusiness: "Service",
          dateOfIncorporationAD: "2025-03-05",
          dateOfIncorporationBS: "2081-12-12",
          firstContactPersonName: "Preeti",
          firstContactFatherName: "Devendra",
          firstContactGrandfatherName: "Gagan",
          firstContactDesignation: "Executive",
          secondContactPersonName: "Bikram",
          secondContactFatherName: "Hari",
          secondContactGrandfatherName: "Ganga",
          secondContactDesignation: "Director",
          fax: "326316",
          companyWebsite: "wertyuij",
        },
        ownershipDetails: {
          firstName: "Privik",
          middleName: "Thapa",
          lastName: "Magar",
          designation: "Director",
          fatherName: "Bikram",
          grandfatherName: "Hari",
          panNumber: "326565",
          email: "privik@gmail.com",
          address: "Kohalpur",
          country: "Nepal",
          province: "Province 5",
          district: "Bardiya",
          municipality: "Kohalpur",
          wardNumber: "6",
          tole: "ShivaNagar",
          postalCode: "22904",
          phoneNumber1: "95541524164851",
          phoneNumber2: "972120.13021",
          citizenshipNumber: "624635641-526545-25",
          citizenshipIssueDistrict: "Banke",
          citizenshipIssueAD: "2025-03-05",
          citizenshipIssueBS: "2081-12-05",
          professionalQualification: "jhgnkhm",
          professionalExperience: "2",
          educationalQualification: "Graduate",
        },
      },
      {
        clientType: "individual",
        status: "pending",
        email: "armita@gmail.com",
        mobileNumber: "216510321",
        panNumber: "2549864",
        password: bcrypt.hashSync("armita", 10),
        isFirstLogin: true,
        addresses: [
          {
            countryOfResidence: "China",
            state: "State 2",
            district: "District 1",
            municipality: "Kohalpur",
            wardNum: "6",
            street: "AadarshNagar",
            addressType: "Corporate Office",
          },
        ],
        depositoryInfo: [
          {
            BOID: "test",
          },
        ],
        bankingInfo: [
          {
            bankName: "Global IME Bank",
            branch: "Kohalpur",
            accountType: "Saving",
            accountNumber: "624634065",
          },
        ],
        documents: [
          {
            fileName: "test",
            fileUrl: "test",
          },
        ],
        individualDetails: {
          firstName: "Privik",
          middleName: "Thapa",
          lastName: "Magar",
          gender: "Male",
          dateOfBirthAD: "2001-01-01",
          dateOfBirthBS: "2058-01-01",
          fatherName: "Bikram Thapa",
          motherName: "Preeti Raskoti",
          grandfatherName: "Hari Bahadur Thapa Magar",
          maritalStatus: "Single",
          nationality: "Nepali",
          financialDetails: "Upto 5,00,000",
          isNRN: false,
          isMinor: false,
          isInvolvedInInvestmentCompany: true,
          citizenshipNumber: "12344",
          citizenshipIssuedDistrict: "test",
          citizenshipIssuedDateAD: "2020-10-10",
          citizenshipIssuedDateBS: "2080-10-10",
        },
        moneyLaunder: {
          isHighRankingPolitician: false,
          isRelatedToHighRankingPolitician: false,
          haveBenefieciary: false,
          felonyRecord: false,
        },
      },
      {
        clientType: "mutual",
        email: "kushal@gmail.com",
        mobileNumber: "985264151",
        status: "verified",
        panNumber: "6254986",
        password: bcrypt.hashSync("kushal", 10),
        isFirstLogin: true,
        companyDetails: {
          companyName: "Petal",
          companyType: "Govt. Owned",
          companyRegistrationNum: "24549",
          isSubsidiary: false,
          isListed: false,
          companyRegistrationAD: "2025-12-05",
          companyRegistrationBS: "2081-12-04",
          contactNumber: "98526463362",
          companyCEOName: "Privik",
          companySecretaryName: "Preeti",
          companyRegistrationOffice: "Kohalpur",
          countryOfRegistration: "Nepal",
          typeOfBusiness: "Service",
          dateOfIncorporationAD: "2025-03-05",
          dateOfIncorporationBS: "2081-12-12",
          firstContactPersonName: "Preeti",
          firstContactFatherName: "Devendra",
          firstContactGrandfatherName: "Gagan",
          firstContactDesignation: "Executive",
          secondContactPersonName: "Bikram",
          secondContactFatherName: "Hari",
          secondContactGrandfatherName: "Ganga",
          secondContactDesignation: "Director",
          fax: "326316",
          companyWebsite: "wertyuij",
        },
        ownershipDetails: {
          firstName: "Privik",
          middleName: "Thapa",
          lastName: "Magar",
          designation: "Director",
          fatherName: "Bikram",
          grandfatherName: "Hari",
          panNumber: "326565",
          email: "privik@gmail.com",
          address: "Kohalpur",
          country: "Nepal",
          province: "Province 5",
          district: "Bardiya",
          municipality: "Kohalpur",
          wardNumber: "6",
          tole: "ShivaNagar",
          postalCode: "22904",
          phoneNumber1: "95541524164851",
          phoneNumber2: "972120.13021",
          citizenshipNumber: "624635641-526545-25",
          citizenshipIssueDistrict: "Banke",
          citizenshipIssueAD: "2025-03-05",
          citizenshipIssueBS: "2081-12-05",
          professionalQualification: "jhgnkhm",
          professionalExperience: "2",
          educationalQualification: "Graduate",
        },
      },
      {
        clientType: "mutual",
        email: "rexshon@gmail.com",
        mobileNumber: "9800000000",
        status: "pending",
        panNumber: "2546514",
        password: bcrypt.hashSync("rexshon", 10),
        isFirstLogin: true,
        companyDetails: {
          companyName: "Petal",
          companyType: "Private",
          companyRegistrationNum: "24549",
          isSubsidiary: false,
          isListed: false,
          companyRegistrationAD: "2025-12-05",
          companyRegistrationBS: "2081-12-04",
          contactNumber: "98526463362",
          companyCEOName: "Privik",
          companySecretaryName: "Preeti",
          companyRegistrationOffice: "Kohalpur",
          countryOfRegistration: "Nepal",
          typeOfBusiness: "Service",
          dateOfIncorporationAD: "2025-03-05",
          dateOfIncorporationBS: "2081-12-12",
          firstContactPersonName: "Preeti",
          firstContactFatherName: "Devendra",
          firstContactGrandfatherName: "Gagan",
          firstContactDesignation: "Executive",
          secondContactPersonName: "Bikram",
          secondContactFatherName: "Hari",
          secondContactGrandfatherName: "Ganga",
          secondContactDesignation: "Director",
          fax: "326316",
          companyWebsite: "wertyuij",
        },
        ownershipDetails: {
          firstName: "Privik",
          middleName: "Thapa",
          lastName: "Magar",
          designation: "Director",
          fatherName: "Bikram",
          grandfatherName: "Hari",
          panNumber: "326565",
          email: "privik@gmail.com",
          address: "Kohalpur",
          country: "Nepal",
          province: "Province 5",
          district: "Bardiya",
          municipality: "Kohalpur",
          wardNumber: "6",
          tole: "ShivaNagar",
          postalCode: "22904",
          phoneNumber1: "95541524164851",
          phoneNumber2: "972120.13021",
          citizenshipNumber: "624635641-526545-25",
          citizenshipIssueDistrict: "Banke",
          citizenshipIssueAD: "2025-03-05",
          citizenshipIssueBS: "2081-12-05",
          professionalQualification: "jhgnkhm",
          professionalExperience: "2",
          educationalQualification: "Graduate",
        },
      },
    ];
    await userSchema.insertMany(users);
    console.log("Seeding completed successfully!");
  } catch (error) {
    console.error("Error during seeding:", error.message);
  } finally {
    console.log(" Disconnecting from database...");
    await mongoose.disconnect();
  }
};

const seedBroker = async () => {
  try {
    console.log("📡 Connecting to Database...");
    await mongoose.connect(envConfig.dbUri);

    console.log("🗑 Clearing existing users...");
    await brokerSchema.deleteMany(); // Clear existing data before seeding
    const broker = [
      {
        name: "broker",
        email: "broker@gmail.com",
        password: bcrypt.hashSync("test123", 10),
        phone: "98151661",
      },
    ];
    await brokerSchema.insertMany(broker);
    console.log("Broker Seeding completed successfully!");
  } catch (error) {
    console.error("Error during seeding:", error.message);
  } finally {
    console.log(" Disconnecting from database...");
    await mongoose.disconnect();
  }
};

seedUsers();
// seedBroker();
